### ISSUE TITLE
Is this doing the same thing as the alibaba rsocket broker? 

### ISSUE THREAD

**Issue by rkklai** [rsocket-broker/rsocket-broker#23]
When I was doing my research on rsocket broker, I found this project and the alibaba-rsocket-broker project which seems more actively maintained. However, this seems to reside on the official repo? What are the differences? Thanks!

**Comment by huahouye** [comment]
see [this issue](https://github.com/alibaba/alibaba-rsocket-broker/issues/70)

**Comment by spencergibb** [comment]
They have similar goals. In fact we just met with Alibaba recently about collaborating, sharing code where possible and more. This project is implementing the routing and forwarding extension specification.

**Comment by rkklai** [comment]
That's great news! Thanks!
